name: Lint & Test

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - tests/**
      - .github/workflows/lint_n_test.yaml
      - pyproject.toml

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Lint with ruff
        run: |
          pipx install ruff==0.0.262
          ruff check .

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with dev

      - name: Migrate database
        run: poetry run pw_migrate migrate --database sqlite:///garendar.db

      - name: Run Tests
        run: poetry run pytest tests -s -v
